### PR TITLE
Update intro

### PR DESCRIPTION
**Pull request by kendoggz**
updating intro text to reference me.

### CODE REVIEW

**Comment by kendoggz** [comment]
replaced "esther" with "ken"

**Comment by gozman** [comment]
Why are you doing a pull request for this? This should stay in your own repository as its specific to your bot.

**Comment by PJRuiz** [comment]
@kendoggz You should fork the repository and then make the changes on the repository in your user

**Comment by johnbeynon** [comment]
I think the instructions should include instructions to either fork from the GitHub repo or clone the app from Heroku and push to your own GitHub account. 

> By clicking on the pencil icon you can edit the document. The keywords are on the left, and the bot's response is on the right. For example, if a user types "hello" then the bot will say "Sweet, let's do this..."

Is confusing people if they are reading this on the projects URL

**Pull request closed without merging**
